config/routes.rb
Rails.application.routes.draw do
  root to: "table#index"
  resources :table, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element.rb
class Element < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/table_controller.rb
class TableController < ApplicationController
  def index
    @elements = Element.all
  end

  def show
    @element = Element.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PeriodicTable</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <h1>Tabela Periódica</h1>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

  

app/views/table/index.html.erb
<table class="first_table">
<% for i in 1..7 do %>
  <tr>
  <% for j in 1..18 do %>
    <td>
    <% @elements.each do |element| %>  
      <% if i == element.ypos.to_i && j == element.xpos.to_i %>
        <%= link_to table_path(id: element) do %>
        <section class="<%=element.category.gsub(/\s+/, '')%>">
          <%= element.number %><br>
          <h5><%= element.symbol %></h5>
          <%= element.name %><br>
          <%= element.atomic_mass %>
        </section>
        <% end %>
      <% end %>
    <% end %>
  
  <% if i == 6 && j == 3 %>
    <h5 style="text-align:center;">57-71</h5>
  <% end %>
  <% if i == 7 && j == 3 %>
    <h5 style="text-align:center;">89-103</h5>
  <% end %>
  
    </td>
  <% end %>
  </tr>
<% end %>
</table>

<table class="second_table">
  <tr>
    <% @elements.each do |element| %>  
      <% if element.category == "lanthanide" %>
        <td>
          <%= link_to table_path(id: element) do %>
            <section class="<%=element.category %>">
              <%= element.number %><br>
              <h5><%= element.symbol %></h5>
              <%= element.name %><br>
              <%= element.atomic_mass %>
            </section>
          <% end %>
        </td>
      <% end %>
    <% end %>
  </tr>
  <tr>
    <% @elements.each do |element| %>  
      <% if element.category == "actinide" %>
        <td>
          <%= link_to table_path(id: element) do %>
            <section class="<%=element.category %>">
              <%= element.number %><br>
              <h5><%= element.symbol %></h5>
              <%= element.name %><br>
              <%= element.atomic_mass %>
            </section>
          <% end %>
        </td>
      <% end %>
    <% end %>
  </tr>
</table>

app/views/table/show.html.erb
  <div class="main">
  
  <div class="leftbox">

    <div >
        <div class="shells">
          <h5>
          <% @element.shells.gsub("[", '').gsub("]", '').split(",").each do |shell| %>
            <%= shell %><br>
          <% end %>
          </h5>
        </div>
        <div>
        <h5><strong><%= @element.number %></strong></h5>
        <h1><%= @element.symbol %></h1>
        <h5><%= @element.name %><br>
        <%= @element.atomic_mass %></h5>
        </div>
    </div> 

    <p class="summary">
    <strong>Summary:</strong>
    <%= @element.summary %>
    </p>
  
  </div>

  <div class="rightbox">
    <table>
        <% if @element.appearance.present? %>
          <tr>
            <td>Appearance</td>
            <td><%= @element.appearance %></td>
          </tr>
        <% end %>
        <tr>
          <td>Atomic mass:</td>
          <td><%= @element.atomic_mass %>
          </td>
        </tr>
        <% if @element.boil.present? %>
          <tr>
            <td>Boil</td>
            <td><%= @element.boil %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Category</td>
          <td><%= @element.category %>
          </td>
        </tr>
        <% if @element.color.present? %>
          <tr>
            <td>Color</td>
            <td><%= @element.color %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Density</td>
          <td><%= @element.density %>
          </td>
        </tr>
        <% if @element.discovered_by.present? %>
          <tr>
            <td>Discovered by</td>
            <td><%= @element.discovered_by %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Melt</td>
          <td><%= @element.melt %>
          </td>
        </tr>
        <% if @element.molar_heat.present? %>
          <tr>
            <td>Molar Heat</td>
            <td><%= @element.molar_heat %>
            </td>
          </tr>
        <% end %>
        <% if @element.named_by.present? %>
          <tr>
            <td>Named by</td>
            <td><%= @element.named_by %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Period</td>
          <td><%= @element.period %>
          </td>
        </tr>
        <tr>
          <td>Phase</td>
          <td><%= @element.phase %>
          </td>
        </tr>
        <tr>
          <td>Source</td>
          <td><%= link_to "Information on Wikipedia", @element.source, target: "_blank" %></td>
        </tr>
        <% if @element.spectral_img.present? %>
          <tr>
            <td>Spectral image</td>
            <td><%= link_to "Image on Wikipedia", @element.spectral_img, target: "_blank" %></td>
          </tr>
        <%end %>
          <tr>
            <td>Shells</td>
            <td><%= @element.shells %></td>
          </tr>
        <% if @element.electron_configuration.present? %>
          <tr>
            <td>Electron configuration</td>
            <td><%= @element.electron_configuration %>
            </td>
          </tr>
        <% end %>
        <% if @element.electron_configuration.present? %>
          <tr>
            <td>Electron configuration semantic</td>
            <td><%= @element.electron_configuration_semantic %>
            </td>
          </tr>
        <% end %>
        <% if @element.electron_affinity.present? %>
          <tr>
            <td>Electron affinity</td>
            <td><%= @element.electron_affinity %>
            </td>
          </tr>
        <% end %>
        <% if @element.electronegativity_pauling.present? %>
          <tr>
            <td>Electronegativity pauling</td>
            <td><%= @element.electronegativity_pauling %>
            </td>
          </tr>
        <% end %>
        <% if @element.ionization_energies.present? %>
          <tr>
            <td>Ionization energies</td>
            <td><%= @element.ionization_energies %>
            </td>
          </tr>
        <% end %>

    </table>
  </div>

</div>